version: "3"
services:
  ldap:
    restart: unless-stopped
    image: dcm4che/slapd-dcm4chee:2.4.50-22.5
    container_name: ldap
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
      - "636:636"
    env_file: docker-compose.env
    volumes:
      - ./data/ldap/data:/var/lib/openldap/openldap-data
      - ./data/ldap/slapd.d:/etc/openldap/slapd.d
  keycloak:
    restart: unless-stopped
    build: ./keycloak
    container_name: keycloak
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8843:8843"
      - "8880:8880"
      - "8990:8990"
      - "8993:8993"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      KEYCLOAK_WAIT_FOR: ldap:389
    depends_on:
      - ldap
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./data/keycloak:/opt/keycloak/standalone
      - ./certs:/opt/keystore
  db:
    restart: unless-stopped
    image: dcm4che/postgres-dcm4chee:12.2-22
    container_name: db
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5433:5432"
    env_file: docker-compose.env
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./data/db:/var/lib/postgresql/data
  arc:
    restart: unless-stopped
    build: ./arc
    container_name: arc
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - keycloak
      - db
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./data/arc:/opt/wildfly/standalone
      - ./certs:/opt/keystore
      - ./data/storage:/storage
  connector:
    restart: unless-stopped
    image: suportebiograph/e-laudos-connector:0.2.1
    container_name: connector
    logging:
      driver: json-file
      options:
        max-size: '10m'
    ports:
      - '8088:8080'
    env_file: docker-compose.env
    depends_on:
      - db
networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: dcm4chee
