version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.50-22.3
    container_name: ldap
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
      - "636:636"
    env_file: docker-compose.env
    volumes:
      - ./data/ldap:/var/lib/openldap/openldap-data
      - ./data/slapd.d:/etc/openldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:10.0.2
    container_name: keycloak
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      KEYCLOAK_WAIT_FOR: ldap:389
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/keycloak:/opt/keycloak/standalone
  db:
    image: dcm4che/postgres-dcm4chee:12.2-22
    container_name: db
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/db:/var/lib/postgresql/data
  arc:
    build: ./arc
    container_name: arc
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - keycloak
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/wildfly:/opt/wildfly/standalone
      - ./data/storage:/storage